### ISSUE TITLE
Default scope does not match README.md

### ISSUE THREAD

**Issue by jochakovsky** [ueberauth/ueberauth_google#12]
README.md states:

By default the requested scope is "profile".

However, the default scope actually seems to be email: https://github.com/ueberauth/ueberauth_google/blob/master/lib/ueberauth/strategy/google.ex#L6

Thanks! Not sure which of the two should be updated.

**Comment by doomspork** [comment]
@jochakovsky if you can confirm that we do not in fact set the `profile` as default scope in the code, we should update the README.
