### ISSUE TITLE
HTTPS Not Working Behind Proxy

### ISSUE THREAD

**Issue by nikkomiu** [ueberauth/ueberauth_google#17]
Using NGINX to do SSL offloading there doesn't seem to be a way to make the OAuth request with a callback URI that uses HTTPS instead of HTTP.

Is there any way to make it possible to either manually specify HTTPS or a Callback URI?

**Comment by doomspork** [comment]
Hi @nikkomiu, you can configure the `callback_path`: https://github.com/ueberauth/ueberauth#customizing-paths

**Comment by nikkomiu** [comment]
That doesn't seem to work with a URL it only seems to work with a path.

**Comment by doomspork** [comment]
@nikkomiu sounds like something that might be worth incorporating into Ueberauth, would you be interested in opening a PR to add this?

**Comment by nikkomiu** [comment]
I can take a look at it! Should I put an issue in on Ueberauth?

**Comment by doomspork** [comment]
Please do!

**Comment by nikkomiu** [comment]
Of course in looking through the source code there is a better way to handle my particular use case. :disappointed:

I can set the `X-Forwarded-Proto` header from my NGINX instance to set https properly.

Perhaps the only thing needed is documentation around this header?

**Comment by hassox** [comment]
Sounds like a plan. @nikkomiu would you be up for a PR?

**Comment by nikkomiu** [comment]
Yea I could do that. Should this go on Uberauth though and not the Google specific one?

**Comment by nikkomiu** [comment]
The solution to my problem was with the NGINX configuration. I needed to add the `X-Forwarded-Proto` header in my NGINX configuration for the site.
