### ISSUE TITLE
How to pass state during the oauth process?

### ISSUE THREAD

**Issue by prashanthsadasivan** [ueberauth/ueberauth_google#26]
Looking at https://developers.google.com/identity/protocols/OAuth2WebServer, I see it's possible to pass `state` as a parameter during the oauth process, and after the oauth process completes, google will pass it back to your application.

I saw that this lib has support for the other parameters like `access_type` and such, I was wondering if it's possible to add support to add `state` dynamically as well?

**Comment by stevedomin** [comment]
@prashanthsadasivan I think `state` may have been removed by error in the last PR: https://github.com/ueberauth/ueberauth_google/commit/360d6049c9d0bd75b7eef916eb425191883c6f8d

**Comment by doomspork** [comment]
@prashanthsadasivan / @stevedomin — TBH I'm not sure why the state variable was removed, I'm going to go back through the history to double check but I think we can safely re-introduced if one of you would like to open the PR.
