### ISSUE TITLE
`default_scope` in README doesn't work

### ISSUE THREAD

**Issue by egeersoz** [ueberauth/ueberauth_google#44]
My config:

```
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [default_scope: "emails profile plus.me", approval_prompt: "force", access_type: "offline"]}
  ]
```

Response from Google:

```
Error: invalid_scope

Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/userinfo.profile], invalid=[emails, plus.me]}
```

**Comment by jcypret** [comment]
@egeersoz I ran into this as well. The README specifies "emails" in default scopes, but should actually be "email" (singular). It's correct in the source code and the query param example: https://github.com/ueberauth/ueberauth_google/blob/3a7949fdc5a007c2a124aa0b6a5bd808688d9a68/lib/ueberauth/strategy/google.ex#L6

**Comment by doomspork** [comment]
@egeersoz or @jcypret, would you mind opening a PR to correct the README?
