### ISSUE TITLE
Getting a 403 error, no details

### ISSUE THREAD

**Issue by egeersoz** [ueberauth/ueberauth_google#45]
I set up my application similar to the example application.

I can reach the consent screen. However, right after I click "allow", I get an error:

```
%Ueberauth.Failure{errors: [%Ueberauth.Failure.Error{message: 403,
   message_key: "OAuth2"}], provider: :google,
 strategy: Ueberauth.Strategy.Google}
```

How do I get more details about this error so that I can troubleshoot?

EDIT: It works if I remove `default_scope: "https://www.googleapis.com/auth/calendar"` from the config. Is there an issue with this scope with regards to this library?

**Comment by egeersoz** [comment]
More details here: https://stackoverflow.com/questions/47778685/google-calendar-api-gives-403-error-during-oauth-even-though-it-seems-to-grant-a

**Comment by doomspork** [comment]
@egeersoz is this related to #44?
