### ISSUE TITLE
Default `prompt` param

### ISSUE THREAD

**Issue by pyromaniac** [ueberauth/ueberauth_google#49]
Hello, seem like it is quite impossible to pass default `prompt` param in provider options. It works only if `prompt` is passed as a query param. Btw, to get `refresh_token` from google you need to pass both `prompt=consent` and `access_type=offline` simultaneously. `approval_prompt` Mentioned in docs doesn't work for this purpose.

**Comment by venkatd** [comment]
Looks like `approval_prompt` has been deprecated in favor of `prompt`. https://github.com/google/oauth2client/issues/453#issuecomment-195379235

So the fix here is to replace the keyword `approval_prompt` with `prompt`
