### ISSUE TITLE
Anti-forgery state token

### ISSUE THREAD

**Issue by mercury2269** [ueberauth/ueberauth_google#5]
From what I could understand with my limited experience with elixir and phoenix, there is no anti forgery token currently created and verified, please correct me if I am wrong and didn't know where to look. 

That's something that's recommended by google open id [implementation guide](https://developers.google.com/identity/protocols/OpenIDConnect#authenticatingtheuser) .

> You must protect the security of your users by preventing request forgery attacks. The first step is creating a unique session token that holds state between your app and the user's client. You later match this unique session token with the authentication response returned by the Google OAuth Login service to verify that the user is making the request and not a malicious attacker. These tokens are often referred to as cross-site request forgery (CSRF) tokens.

**Comment by hassox** [comment]
@mercury2269 I believe this is what the 'state' variable is for.

https://github.com/ueberauth/ueberauth_google/blob/master/lib/ueberauth/strategy/google.ex#L20
