### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Tsuyoshi84** [ueberauth/ueberauth_google#56]
It's been almost one year since the latest version, 0.7, has been released, and some bug fixes have been made since then. I think it would make sense to release the current code as the latest version on Hex.
Actually, I was struggling to deal with the problem that has been fixed by #55, as 0.7 does not include it. So, I'd appreciate if the new version  will be released 😃

**Comment by yordis** [comment]
@Tsuyoshi84 will do upcoming week.

**Comment by gpmcadam** [comment]
Any news on a release? Eagerly waiting #55

**Comment by doomspork** [comment]
0.8.0 has been released.  Sorry for the delays.
