### ISSUE TITLE
Upgrade/allow oauth2 to be 2.0

### ISSUE THREAD

**Issue by PragTob** [ueberauth/ueberauth_google#67]
oauth2 was [semi recently upgraded to 2.0](https://github.com/scrogson/oauth2/blob/master/CHANGELOG.md#v200-2019-07-15) with a fix that seems important and relevant. Would be nice to also include that in a future release.

Also, thanks for the great library! :wave: :tada:

**Comment by tajchumber** [comment]
hello @PragTob we will look into it! :)
You are welcome to contribute with PRs as well if you want!

**Comment by PragTob** [comment]
@tajchumber I can happily do a PR allowing OAuth 2.0 just not to sure about the details/specifics as I'm unsure if the "possibly backwards compatible" part applies to this lib or not.

The big PR seems to be this https://github.com/scrogson/oauth2/pull/131 which fixes https://github.com/scrogson/oauth2/issues/128 which is a security related issue.
