### ISSUE TITLE
hexdocs has a bug in it

### ISSUE THREAD

**Issue by Trevoke** [ueberauth/ueberauth_google#7]
The hexdocs show

```elixir
config :ueberauth, Ueberauth,
  providers: [
    google: [ { Ueberauth.Strategy.Google, [] } ]
  ]
```

It should be, like in the README,

```elixir
config :ueberauth, Ueberauth,
  providers: [
    google: { Ueberauth.Strategy.Google, [] }
  ]
```

**Comment by doomspork** [comment]
Good catch @Trevoke, could you open a PR with the fix?

**Comment by Trevoke** [comment]
Of course. I just don't know where the hexdocs are stored. Point me in the right direction and I'll fix it.

**Comment by Trevoke** [comment]
It looks like one of the maintainers may need to run `mix hex.docs`. I don't think I can do this. Sorry.

https://hex.pm/docs/tasks#hex_docs

**Comment by doomspork** [comment]
I pushed the updated docs, it's fixed now @Trevoke.

**Comment by Trevoke** [comment]
Awesome, thank you!

And you're welcome; isn't this what open source is all about? :)
