### ISSUE TITLE
Hackney not running?

### ISSUE THREAD

**Issue by Trevoke** [ueberauth/ueberauth_google#8]
Hi,

I tried to set up Ueberauth with Google auth recently and [ran into an error](https://stackoverflow.com/questions/36193141/phoenix-ueberauth-google-heroku-internal-server-error/36195471?noredirect=1#comment60040326_36195471) due to hackney not running. 

The ueberauth example app seems to run fine, so I'm wondering what I might be missing (or what may have changed recently that is not reflected in the example app) ?

**Comment by doomspork** [comment]
@trevoke could you share your code, specifically `mix.exs`?

**Comment by doomspork** [comment]
Resolved in Slack, `ueberauth_google` was missing from application list.
